[package]
name = "coolcoin"
version = "0.1.0"
authors = ["Nikola Stojiljkovic <nikolavla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
bincode = "1.3.3"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.67"
serde-big-array = "0.3.2"
sha2 = "0.9.6"
hex = "0.4.3"

[lib]
name = "coolcoin_lib"
path = "src/lib.rs"

[[bin]]
name = "coolcoin"
path = "src/bin/main.rs"